version: 0.2

phases:
  install:
    run-as: root
    commands:
      - apt-get update && apt-get install nodejs npm -y
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
