/*
  movie_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  title varchar(1000) DEFAULT NULL,
  budget INT DEFAULT NULL,
  homepage varchar(1000) DEFAULT NULL,
  overview varchar(1000) DEFAULT NULL,
  popularity decimal(12,6) DEFAULT NULL,
  release_date date DEFAULT NULL,
  revenue BIGINT DEFAULT NULL,
  runtime INT DEFAULT NULL,
  CONSTRAINT pk_movie PRIMARY KEY (movie_id)
*/

const Actor = (sequelize, Sequelize) => sequelize.define("actor", {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: true,
    primaryKey: true
  },
    name: {
      type: Sequelize.STRING,
      allowNull: true
    },
    age: {
      type: Sequelize.INTEGER,
      allowNull: true
    },
    gender: {
      type: Sequelize.STRING,
      allowNull: true
    },
    popular: {
      type: Sequelize.INTEGER,
      allowNull: true,
      validate: {
        isDecimal: true,
        max: 150,
        min: 0,
      },
    },
    birthday: {
      type: Sequelize.DATE,
      allowNull: true
    },
    valued: {
      type: Sequelize.INTEGER,
      allowNull: true
    },
  }
);

module.exports = Actor;
