/*
  movie_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  title varchar(1000) DEFAULT NULL,
  budget INT DEFAULT NULL,
  homepage varchar(1000) DEFAULT NULL,
  overview varchar(1000) DEFAULT NULL,
  popularity decimal(12,6) DEFAULT NULL,
  release_date date DEFAULT NULL,
  revenue BIGINT DEFAULT NULL,
  runtime INT DEFAULT NULL,
  CONSTRAINT pk_movie PRIMARY KEY (movie_id)
*/

const Food = (sequelize, Sequelize) => sequelize.define("food", {
    id: {
      type: Sequelize.INTEGER,
      primaryKey: true,
      autoIncrement: true // Automatically gets converted to SERIAL for postgres
    },
    name: {
      type: Sequelize.STRING,
      allowNull: true
    },
    protein: {
      type: Sequelize.INTEGER,
      allowNull: true
    },
    calories: {
      type: Sequelize.INTEGER,
      allowNull: true
    },
    fat: {
      type: Sequelize.INTEGER,
      allowNull: true
    },
    size: {
      type: Sequelize.INTEGER,
      allowNull: true
    },
    portion: {
      type: Sequelize.STRING,
      allowNull: true
    },
    category: {
      type: Sequelize.STRING,
      allowNull: true
    },
  }
);

module.exports = Food;
