/*
  movie_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  title varchar(1000) DEFAULT NULL,
  budget INT DEFAULT NULL,
  homepage varchar(1000) DEFAULT NULL,
  overview varchar(1000) DEFAULT NULL,
  popularity decimal(12,6) DEFAULT NULL,
  release_date date DEFAULT NULL,
  revenue BIGINT DEFAULT NULL,
  runtime INT DEFAULT NULL,
  CONSTRAINT pk_movie PRIMARY KEY (movie_id)
*/

const Movie = (sequelize, Sequelize, DataTypes) => sequelize.define("movie", {
    movie_id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true // Automatically gets converted to SERIAL for postgres
    },
    title: {
      type: DataTypes.STRING(1000),
      allowNull: true
    },
    budget: {
      type: DataTypes.INTEGER,
      allowNull: true
    },
    homepage: {
      type: DataTypes.STRING(1000),
      allowNull: true
    },
    overview: {
      type: DataTypes.STRING(1000),
      allowNull: true
    },
    popularity: {
      type: DataTypes.DECIMAL(12, 6),
      allowNull: true,
      validate: {
        isDecimal: true,
        max: 150,
        min: 0,
      },
    },
    release_date: {
      type: DataTypes.DATE,
      allowNull: true
    },
    revenue: {
      type: DataTypes.BIGINT,
      allowNull: true
    },
    runtime: {
      type: DataTypes.INTEGER,
      validate: {
        isInt: true
      },
      allowNull: true
    }
  }
);

module.exports = Movie;
